# Generated by Django 5.2.6 on 2025-11-01 05:53

import apps.pedidos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_cliente_pedido_user_remove_pedido_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='code',
            field=models.CharField(default=apps.pedidos.models.gerar_code, max_length=12, unique=True),
        ),
    ]
