# Generated by Django 5.2.6 on 2025-11-07 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='data',
            field=models.DateField(blank=True, help_text='Data de retirada/entrega', null=True),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
