# Generated by Django 5.2.6 on 2025-11-07 03:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_produto_slug'),
        ('pedidos', '0004_alter_pedidoitem_data_alter_pedidoitem_pedido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrinhoitem',
            options={'ordering': ['adicionado_em']},
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='user',
        ),
        migrations.AddField(
            model_name='carrinhoitem',
            name='adicionado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrinhoitem',
            name='data',
            field=models.DateField(blank=True, help_text='Data de retirada ou entrega', null=True),
        ),
        migrations.AlterField(
            model_name='carrinhoitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho_items', to='core.produto'),
        ),
        migrations.AlterField(
            model_name='carrinhoitem',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
