# Generated by Django 5.2.6 on 2025-11-14 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20251109_0203'),
        ('pedidos', '0007_alter_carrinho_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='metodo_pagamento',
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='carrinho', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrinhoitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto'),
        ),
    ]
