# Generated by Django 5.2.6 on 2025-11-14 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20251109_0203'),
        ('pedidos', '0008_remove_pedido_metodo_pagamento_alter_carrinho_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='code',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lojaperfil'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('carrinho', 'Carrinho'), ('pendente', 'Aguardando loja'), ('pago', 'Pago'), ('entregue', 'Entregue')], default='carrinho', max_length=20),
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
        ),
        migrations.DeleteModel(
            name='PedidoItem',
        ),
    ]
