# Generated by Django 5.2.6 on 2025-11-14 15:40

import apps.pedidos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20251109_0203'),
        ('pedidos', '0009_remove_pedido_code_remove_pedido_total_and_more'),
        ('users', '0010_alter_pagamento_metodo_remove_pagamento_confirmado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='code',
            field=models.CharField(default=apps.pedidos.models.gerar_code, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.pagamento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrinho', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carrinhoitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho_items', to='core.produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='loja',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.lojaperfil'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('preparando', 'Preparando'), ('a caminho', 'A caminho'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, help_text='Data de retirada/entrega', null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
    ]
