# Generated by Django 5.2.6 on 2025-11-14 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20251109_0203'),
        ('pedidos', '0010_pedido_code_pedido_metodo_pagamento_pedido_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrinhoitem',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='carrinhoitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='criado_em',
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='carrinho', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrinhoitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto'),
        ),
        migrations.RemoveField(
            model_name='carrinhoitem',
            name='adicionado_em',
        ),
        migrations.RemoveField(
            model_name='carrinhoitem',
            name='data',
        ),
    ]
