# Generated by Django 5.2.6 on 2025-11-14 19:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_alter_carrinhoitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinhoitem',
            name='adicionado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
