# Generated by Django 5.2.7 on 2025-10-18 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.URLField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pratos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade_disponivel', models.PositiveIntegerField(default=0)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativa', models.BooleanField(default=True)),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='cardapio.prato')),
            ],
            options={
                'ordering': ['data'],
                'unique_together': {('prato', 'data')},
            },
        ),
    ]
