# Generated by Django 5.2.6 on 2025-11-05 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lojaperfil_user_alter_produto_loja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='cardapio',
            name='nome',
        ),
        migrations.AddField(
            model_name='cardapio',
            name='produtos',
            field=models.ManyToManyField(blank=True, related_name='cardapios', to='core.produto'),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='loja',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cardapio', to='core.lojaperfil'),
        ),
        migrations.DeleteModel(
            name='CardapioItem',
        ),
    ]
