# Generated by Django 5.2.6 on 2025-11-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cardapio_data_criacao_remove_cardapio_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='produtos',
            field=models.ManyToManyField(related_name='cardapios', to='core.produto'),
        ),
    ]
