# Generated by Django 5.2.6 on 2025-11-06 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_lojaperfil_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='slug',
        ),
    ]
