# Generated by Django 5.2.6 on 2025-11-09 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_produto_atualizada_em_produto_disponivel_and_more'),
        ('users', '0006_remove_endereco_user_endereco_complemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lojaperfil',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to='users.endereco'),
        ),
    ]
