# Generated by Django 5.2.6 on 2025-11-09 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_lojaperfil_endereco'),
        ('core', '0010_fix_endereco_loja_unico'),
    ]

    operations = [
    ]
