# Generated by Django 5.2.6 on 2025-11-11 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_endereco_user_endereco_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='metodo_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.pagamento'),
        ),
    ]
