# Generated by Django 5.2.6 on 2025-11-14 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_remove_pedido_metodo_pagamento_alter_carrinho_user_and_more'),
        ('users', '0007_pagamento_metodo_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='metodo_pagamento',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pedidos.pedido'),
        ),
    ]
