# Generated by Django 5.2.6 on 2025-11-14 03:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_remove_pedido_code_remove_pedido_total_and_more'),
        ('users', '0008_remove_pagamento_metodo_pagamento_pagamento_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='chave_pix',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='nome_no_cartao',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='numero_cartao',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='validade',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='pedido',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cartao', 'Cartão'), ('pix', 'PIX'), ('dinheiro', 'Dinheiro')], max_length=20)),
                ('apelido', models.CharField(max_length=50)),
                ('nome_no_cartao', models.CharField(blank=True, max_length=120, null=True)),
                ('numero', models.CharField(blank=True, max_length=30, null=True)),
                ('validade', models.CharField(blank=True, max_length=7, null=True)),
                ('cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('chave_pix', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pagamento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.metodopagamento'),
        ),
    ]
