# Generated by Django 5.2.6 on 2025-11-14 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_pagamento_ativo_remove_pagamento_chave_pix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(choices=[('cartao', 'Cartão de Crédito/Débito'), ('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='confirmado',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='pedido',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='cvv',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='nome_no_cartao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='numero_cartao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='validade',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MetodoPagamento',
        ),
    ]
